<a href="https://colab.research.google.com/github/Praneashram/Priority1/blob/main/SPT1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [158]:
import pandas as pd
import numpy as np
import itertools
from itertools import combinations

In [159]:
dataFrame = pd.read_csv('https://raw.githubusercontent.com/Praneashram/Priority1/main/Priority2.csv')

In [160]:
#Arrival time based sorting
#dataFrame = dataFrame.sort_values('Arrival Time', ascending=True, ignore_index=True)
temp = dataFrame.sort_values(['Arrival Time', 'Processing Time', 'Priority'], ascending=[True, True, True],ignore_index=True)
temp

   Process  Processing Time  Priority  Arrival Time
0       P1                1         2             0
1       P6               29         1             0
2       P4                2         1             2
3       P2               21         0             5
4       P5                5         4             9
5       P3                8         3            12
6      P11               13         2            17
7       P8                3         0            18
8      P10               18         2            19
9      P13               21         1            19
10      P7               11         5            20
11     P14               26         3            25
12     P12                4         2            30
13     P15               27         3            32
14      P9                7         1            39

In [161]:
minArrivalTime = min(list(dataFrame['Arrival Time']))
startingProcesses = dataFrame[dataFrame['Arrival Time'] == minArrivalTime]
startingProcesses = startingProcesses.sort_values('Processing Time', ascending=True, ignore_index=True)
startingProcessesList = list(startingProcesses['Process'])
#print(startingProcessesList)
for s in startingProcessesList:
  startingIndex = dataFrame[dataFrame['Process'] == s].index
  dataFrame = dataFrame.drop(startingIndex)
dataFrame = dataFrame.sort_values('Processing Time', ascending=True, ignore_index=True)
dataFrame = startingProcesses.append(dataFrame)
dataFrame = dataFrame.reset_index(drop=True)
dataFrame
#data = dataFrame[['Process'],ignore_index=True]
#data

   Process  Processing Time  Priority  Arrival Time
0       P1                1         2             0
1       P6               29         1             0
2       P4                2         1             2
3       P8                3         0            18
4      P12                4         2            30
5       P5                5         4             9
6       P9                7         1            39
7       P3                8         3            12
8       P7               11         5            20
9      P11               13         2            17
10     P10               18         2            19
11      P2               21         0             5
12     P13               21         1            19
13     P14               26         3            25
14     P15               27         3            32

In [162]:
completed = []
waiting = []
entryTimes = []
endTimes = []
entryTime = -1
endTime = min(temp['Arrival Time'])
while(len(completed) != len(temp['Process'])):
  for idx, val in dataFrame.iterrows():
    if(val['Process'] not in completed):
      entryTime = endTime
      #print(val['Process'])
      if val['Arrival Time'] <= entryTime:
        completed.append(val['Process'])
        entryTimes.append(entryTime)
        endTime = entryTime + val['Processing Time']
        endTimes.append(endTime)
        break
#print(completed)

In [163]:
#sorted1 = pd.DataFrame(dataFrame, columns = ['Process'])
sorted1 = pd.DataFrame(entryTimes, columns = ['Entry Time'])
sorted2 = pd.DataFrame(endTimes, columns = ['End Time'])
sorted_final = pd.concat([dataFrame,sorted1,sorted2], axis=1)
sorted_final['Turnaround Time'] = sorted_final['End Time'] - sorted_final['Arrival Time']
sorted_final['Waiting Time'] = sorted_final['Entry Time'] - sorted_final['Arrival Time']
sorted_final

   Process  Processing Time  Priority  ...  End Time  Turnaround Time  Waiting Time
0       P1                1         2  ...         1                1             0
1       P6               29         1  ...        30               30             1
2       P4                2         1  ...        32               30            28
3       P8                3         0  ...        35               17            14
4      P12                4         2  ...        39                9             5
5       P5                5         4  ...        44               35            30
6       P9                7         1  ...        51               12             5
7       P3                8         3  ...        59               47            39
8       P7               11         5  ...        70               50            39
9      P11               13         2  ...        83               66            53
10     P10               18         2  ...       101               82            64
11      P2               21         0  ...       122              117            96
12     P13               21         1  ...       143              124           103
13     P14               26         3  ...       169              144           118
14     P15               27         3  ...       196              164           137

[15 rows x 8 columns]

In [164]:
waiting = []
turnaround = []
sum_waiting_time = 0
sum_turnaround_time = 0
avg_waiting_time = 0
avg_turnaround_time = 0
for index, row in sorted_final.iterrows():
  wait = row['Waiting Time']
  turn = row['Turnaround Time']
  waiting.append(wait)
  turnaround.append(turn)

waiting = np.array(waiting)
turnaround = np.array(turnaround)
#print(waiting)
#print(turnaround)
#sum of waiting time for all the processes are calculated
for i in range(waiting.shape[0]):
  sum_waiting_time+=waiting[i]
#sum of turnaround time for all the processes are calculated
for i in range(turnaround.shape[0]):
  sum_turnaround_time+=turnaround[i]

avg_turnaround_time= sum_turnaround_time/len(entryTimes)
avg_waiting_time= sum_waiting_time/len(entryTimes)

print('average waiting time =', avg_waiting_time)
print('average turnaround time =', avg_turnaround_time)

average waiting time = 48.8
average turnaround time = 61.86666666666667